import type { CSSProperties, ReactNode } from "react";

// Original static demonstrations ported from the approved portrait preview.
// Illustration content is never client work or a measured result.
const examples: Record<string, { title: string; body: ReactNode }> = {
  "business-website": { title: "Your business", body: (<><div className="example-site-nav"><span>Services</span><span>Contact</span></div><strong className="example-display">Good services.<br />Easy to find.</strong><div className="example-service-lines"><span>Consultations</span><span>Ongoing support</span></div><span className="example-action">Make an enquiry <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg></span></>) },
  "commerce-booking": { title: "Choose a time", body: (<><div className="example-date"><strong>Tuesday</strong><span>Consultation</span></div><div className="example-slots"><span>10:00</span><span className="chosen">14:30</span><span>16:00</span></div><div className="example-confirmation"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg><div><strong>Booking confirmed</strong><span>Tuesday at 14:30</span></div></div></>) },
  "digital-product": { title: "Project requests", body: (<><div className="example-row"><span>Website update</span><span className="example-state">In progress</span></div><div className="example-row"><span>New report</span><span className="example-state">Review ready</span></div><div className="example-detail"><strong>Website update</strong><span>Review the contact page.</span></div></>) },
  "business-systems": { title: "Team requests", body: (<><div className="example-columns"><span>Request</span><span>Owner</span></div><div className="example-row"><span>Stock check</span><strong>Operations</strong></div><div className="example-row"><span>Supplier record</span><strong>Finance</strong></div><div className="example-note">Assigned work, visible responsibilities.</div></>) },
  "workflow-automation": { title: "Enquiry follow-up", body: (<><ol className="example-sequence"><li><span>Capture the enquiry</span><small>Website form</small></li><li><span>Create a CRM record</span><small>Mapped contact details</small></li><li><span>Arrange a follow-up</span><small>Task for the team</small></li></ol></>) },
  "system-integration": { title: "Connect the records", body: (<><div className="example-mapping"><div><strong>Website</strong><span>Name</span><span>Email</span></div><div className="mapping-arrow"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg></div><div><strong>CRM</strong><span>Contact name</span><span>Contact email</span></div></div><div className="example-note">Map fields. Check duplicates. Sync.</div></>) },
  "knowledge-assistant": { title: "Knowledge search", body: (<><div className="example-question">What happens during onboarding?</div><div className="example-answer">Complete the checklist, then request access.<span className="example-source">Source: sample onboarding guide</span></div></>) },
  "ai-workflows": { title: "An action to review", body: (<><strong className="example-task">Prepare a follow-up email</strong><div className="example-detail"><span>Use the enquiry details.<br />Keep the draft ready for review.</span></div><div className="example-approval"><span className="example-state">Awaiting approval</span><span>Review before sending</span></div></>) },
  "document-processing": { title: "Document to record", body: (<><div className="example-document"><span>Sample invoice</span><strong>INV-001</strong></div><dl className="example-fields"><div><dt>Reference</dt><dd>INV-001</dd></div><div><dt>Supplier</dt><dd>Sample supplier</dd></div></dl><div className="example-review"><span className="example-state quiet">Review required</span><span>Check the extracted fields</span></div></>) },
  "data-foundations": { title: "Prepare an import", body: (<><div className="example-quality"><div><span>Record A</span><span className="example-state quiet">Duplicate</span></div><div><span>Record B</span><span className="example-state">Complete</span></div><div><span>Record C</span><span className="example-state quiet">Missing email</span></div></div><div className="example-note">Resolve issues before importing.</div></>) },
  "reporting": { title: "Requests by week", body: (<><div className="example-chart" aria-label="Example data: week one 12, week two 20, week three 16, week four 24 requests"><div><span>12</span><i style={{"--bar-height":"36px"} as CSSProperties} aria-hidden="true"></i><small>W1</small></div><div><span>20</span><i style={{"--bar-height":"60px"} as CSSProperties} aria-hidden="true"></i><small>W2</small></div><div><span>16</span><i style={{"--bar-height":"48px"} as CSSProperties} aria-hidden="true"></i><small>W3</small></div><div><span>24</span><i style={{"--bar-height":"72px"} as CSSProperties} aria-hidden="true"></i><small>W4</small></div></div><div className="example-chart-note">Request count · example data</div></>) },
  "analysis-models": { title: "What takes longest?", body: (<><div className="example-columns"><span>Request type</span><span>Median time</span></div><div className="example-row"><span>New setup</span><strong>4 days</strong></div><div className="example-row"><span>Updates</span><strong>2 days</strong></div><div className="example-note">Example data for an exploratory comparison.</div></>) },
  "system-improvements": { title: "Make the next step clear", body: (<><div className="example-before-after"><div><strong>Before</strong><span className="example-form-field">Contact</span><span className="example-muted-action">Send</span></div><div><strong>After</strong><span className="example-form-field">Your email</span><span className="example-form-field">Your message</span><span className="example-action compact">Preview message</span></div></div></>) },
  "ongoing-support": { title: "A prioritised work queue", body: (<><div className="example-support-group"><strong>Next</strong><span>Improve search</span><span>Check the import process</span></div><div className="example-release"><strong>Release note</strong><span>Contact labels clarified.</span></div></>) },
};

export function ServiceExample({ id }: { id: string }) {
  const example = examples[id];
  if (!example) return null;
  return <figure className="service-example" data-example={id}><div className="example-window"><div className="example-top"><strong>{example.title}</strong><span className="example-mark" aria-hidden="true" /></div><div className="example-content">{example.body}</div></div><figcaption>Illustrative example</figcaption></figure>;
}

export function BriefExample() { return <figure className="brief-art"><div className="brief-example"><blockquote>“We get enquiries in three places and lose track of follow-ups.”</blockquote><div className="brief-arrow" aria-hidden="true"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg></div><dl><div><dt>Goal</dt><dd>Keep follow-ups visible</dd></div><div><dt>Today</dt><dd>Website, messages, spreadsheet</dd></div><div><dt>First step</dt><dd>Map the current enquiry journey</dd></div></dl></div><figcaption>Illustrative example: from a rough request to a starting brief.</figcaption></figure>; }
